import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.EventQueue;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

public class LogIn 
{
	static JFrame frame;
	JFrame SignUpFrame;
	private static JTextField userField;
	private static JPasswordField passwordField;
	private JPasswordField emailPass;
	static MySQLAccess connect = new MySQLAccess();
	static msgBoxx email;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) 
	{
		EventQueue.invokeLater(new Runnable() 
		{
			public void run() 
			{
				try 
				{
					LogIn window = new LogIn();
					window.frame.setVisible(true);
					
					connect.connectDataBase();
				} 
				catch (Exception e) 
				{
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public LogIn() 
	{
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() 
	{
		//create the login window
		frame = new JFrame("Log In");
		frame.getContentPane().setBackground(Color.GRAY);
		frame.setBounds(100, 100, 666, 291);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		JLabel lblUsername = new JLabel("Username:");
		lblUsername.setFont(new Font("Tahoma", Font.PLAIN, 16));
		
		userField = new JTextField(30);
		userField.setFont(new Font("Tahoma", Font.PLAIN, 16));
		
		JLabel lblPassword = new JLabel("Password:");
		lblPassword.setFont(new Font("Tahoma", Font.PLAIN, 16));
		
		passwordField = new JPasswordField(30);
		passwordField.setFont(new Font("Tahoma", Font.PLAIN, 16));
		
		JButton btnLogin = new JButton("LOGIN");
		btnLogin.setFont(new Font("Tahoma", Font.PLAIN, 16));
		btnLogin.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent e)
			{
				try
				{
					connect.logIn(userField.getText(), passwordField.getText());
				}
				catch(Exception e1)
				{
					e1.printStackTrace();
				}
			}
		});//new emailWindow());
		btnLogin.setBounds(189, 173, 117, 29);
		
		JLabel SignUp = new JLabel("No account?");
		SignUp.setFont(new Font("Tahoma", Font.PLAIN, 16));
		
		JButton signButton = new JButton("Sign Up!");
		signButton.setFont(new Font("Tahoma", Font.PLAIN, 16));
		signButton.addActionListener(new signWindow());
		
		JSeparator separator = new JSeparator();
		
		//layout for the labels and buttons generated by Eclipse Window Builder
		GroupLayout groupLayout = new GroupLayout(frame.getContentPane());
		groupLayout.setHorizontalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(20)
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addGroup(groupLayout.createSequentialGroup()
							.addComponent(separator, GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
							.addContainerGap())
						.addGroup(groupLayout.createSequentialGroup()
							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(lblPassword, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lblUsername, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
							.addGap(18)
							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
								.addComponent(passwordField, GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
								.addComponent(userField, GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
							.addGap(77)
							.addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
							.addGap(32))))
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(205)
					.addComponent(SignUp)
					.addGap(18)
					.addComponent(signButton)
					.addContainerGap(247, Short.MAX_VALUE))
		);
		groupLayout.setVerticalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(groupLayout.createSequentialGroup()
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addGroup(groupLayout.createSequentialGroup()
							.addGap(8)
							.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblUsername, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
								.addComponent(userField, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblPassword)
								.addComponent(passwordField, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)))
						.addGroup(groupLayout.createSequentialGroup()
							.addGap(22)
							.addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)))
					.addGap(50)
					.addComponent(separator, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(38)
					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
						.addComponent(SignUp)
						.addComponent(signButton))
					.addContainerGap(40, Short.MAX_VALUE))
		);
		frame.getContentPane().setLayout(groupLayout);
	}
	
	//creates the signup window
	public class signWindow implements ActionListener
	{
		public void actionPerformed(ActionEvent e)
		{
			frame.dispose();
			SignUpWindow signUp = new SignUpWindow();
		}
	}
	
	//clears the textfields in the login page when a user logs out
	public static void clearTextField()
	{
		userField.setText("");
		passwordField.setText("");
	}
}